/*
	swadExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "swadExample.h"
#import "swad.h"

@implementation swadExample

- (void)run {
	// Create the service
	swad* service = [swad service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";

	// Returns int. Service definition of function swad__getCourses
	[service getCourses:self action:@selector(getCoursesHandler:) wsKey: @""];

	// Returns int. Service definition of function swad__getNotifications
	[service getNotifications:self action:@selector(getNotificationsHandler:) wsKey: @"" beginTime: 0];

	// Returns int. Service definition of function swad__getTestConfig
	[service getTestConfig:self action:@selector(getTestConfigHandler:) wsKey: @"" courseCode: 0];

	// Returns NSMutableArray*. Service definition of function swad__getTests
	[service getTests:self action:@selector(getTestsHandler:) wsKey: @"" courseCode: 0 beginTime: 0];

	// Returns int. Service definition of function swad__getUsers
	[service getUsers:self action:@selector(getUsersHandler:) wsKey: @"" courseCode: 0 groupCode: 0 userTypeCode: 0];

	// Returns int. Service definition of function swad__loginBySession
	[service loginBySession:self action:@selector(loginBySessionHandler:) sessionID: @""];

	// Returns int. Service definition of function swad__loginByUserPassword
	[service loginByUserPassword:self action:@selector(loginByUserPasswordHandler:) userID: @"" userPassword: @""];

	// Returns int. Service definition of function swad__loginByUserPasswordKey
	[service loginByUserPasswordKey:self action:@selector(loginByUserPasswordKeyHandler:) userID: @"diegort" userPassword: @"3ef7e160720d69dea5a5ec2aadad59ce01f5ef23972501b459041e80bf27b0d01bc2f0f080d8b4fae867882a1252cf5a9a2ba97440813d55f436423b91413375" appKey: @"HTCDesire"];

	// Returns int. Service definition of function swad__sendMessage
	[service sendMessage:self action:@selector(sendMessageHandler:) wsKey: @"" messageCode: 0 to: @"" subject: @"" body: @""];
}

	

// Handle the response from getCourses.
		
- (void) getCoursesHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"getCourses returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from getNotifications.
		
- (void) getNotificationsHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"getNotifications returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from getTestConfig.
		
- (void) getTestConfigHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"getTestConfig returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from getTests.
		
- (void) getTestsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"getTests returned the value: %@", result);
			
}
	

// Handle the response from getUsers.
		
- (void) getUsersHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"getUsers returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from loginBySession.
		
- (void) loginBySessionHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"loginBySession returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from loginByUserPassword.
		
- (void) loginByUserPasswordHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"loginByUserPassword returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from loginByUserPasswordKey.
		
- (void) loginByUserPasswordKeyHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"loginByUserPasswordKey returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

// Handle the response from sendMessage.
		
- (void) sendMessageHandler: (int) value {
			

	// Do something with the int result
		
	NSLog(@"sendMessage returned the value: %@", [NSNumber numberWithInt:value]);
			
}
	

@end
		